export const mockUsers = [
  {
    id: 1,
    username: 'admin',
    email: 'admin@djportal.com',
    password: 'admin123',
    role: 'admin',
    status: 'approved',
    namaLengkap: 'Admin Portal',
    phone: '081234567890',
    createdAt: '2024-01-10',
  },
  {
    id: 2,
    username: 'dualipa_dj',
    email: 'dua@email.com',
    password: 'pass123',
    role: 'user',
    status: 'approved',
    namaLengkap: 'Dua Lipa',
    phone: '081987654321',
    createdAt: '2024-01-11',
  },
  {
    id: 3,
    username: 'weeknd_rm',
    email: 'weeknd@email.com',
    password: 'pass123',
    role: 'user',
    status: 'pending',
    namaLengkap: 'The Weeknd',
    phone: '082123456789',
    createdAt: '2024-01-15',
  },
];

export const mockTracks = [
  {
    id: 1,
    judul: 'Levitating',
    remixer: 'Dua Lipa',
    album: 'Future Nostalgia',
    tahun: 2020,
    genre: 'Disco Pop',
    uploadedBy: 'dualipa_dj',
    fileUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    coverUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=300&h=300&fit=crop',
    folderPath: 'Dua Lipa/audio/Levitating.mp3',
    createdAt: '2024-01-12',
    downloadCount: 45,
  },
  {
    id: 2,
    judul: "Don't Start Now",
    remixer: 'Dua Lipa',
    album: 'Future Nostalgia',
    tahun: 2019,
    genre: 'Disco Pop',
    uploadedBy: 'dualipa_dj',
    fileUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
    coverUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop',
    folderPath: "Dua Lipa/audio/Don't Start Now.mp3",
    createdAt: '2024-01-13',
    downloadCount: 32,
  },
  {
    id: 3,
    judul: 'Blinding Lights',
    remixer: 'The Weeknd',
    album: 'After Hours',
    tahun: 2019,
    genre: 'Synthwave',
    uploadedBy: 'dualipa_dj',
    fileUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    coverUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=300&h=300&fit=crop',
    folderPath: 'The Weeknd/audio/Blinding Lights.mp3',
    createdAt: '2024-01-14',
    downloadCount: 78,
  },
  {
    id: 4,
    judul: 'Save Your Tears',
    remixer: 'The Weeknd',
    album: 'After Hours',
    tahun: 2020,
    genre: 'Synthwave',
    uploadedBy: 'dualipa_dj',
    fileUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    coverUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=300&h=300&fit=crop',
    folderPath: 'The Weeknd/audio/Save Your Tears.mp3',
    createdAt: '2024-01-15',
    downloadCount: 56,
  },
  {
    id: 5,
    judul: 'Peaches',
    remixer: 'Justin Bieber',
    album: 'Justice',
    tahun: 2021,
    genre: 'Pop',
    uploadedBy: 'dualipa_dj',
    fileUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    coverUrl: 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=300&h=300&fit=crop',
    folderPath: 'Justin Bieber/audio/Peaches.mp3',
    createdAt: '2024-01-16',
    downloadCount: 23,
  },
];

export const genres = [
  'Disco Pop',
  'Synthwave',
  'Pop',
  'Deep House',
  'Techno',
  'Drum & Bass',
  'Trap',
  'Hip Hop',
  'Electronic',
];
